name: com_test_testapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  video_player: ^2.7.2
  chewie: ^1.5.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_dotenv: ^5.1.0
  youtube_player_iframe: ^5.2.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
